"use client";

import { useEffect, useState, useTransition } from "react";
import { shrinkImage } from "@/lib/images/shrink-image";
import { getLocalDb } from "@/lib/local-db/client";
import { addLocalActivity, createLocalMaintenance, loadLocalMaintenanceDetail, loadLocalWorkOrders, loadMaintenanceOfflineContext, queueMaintenanceMutation, queueMaintenancePhoto } from "@/lib/maintenance/offline";
import { MAINTENANCE_CATEGORIES, MAINTENANCE_PRIORITIES, type MaintenanceDetail, type MaintenanceRoomOption, type MaintenanceStaffOption, type MaintenanceWorkOrder } from "@/lib/maintenance/types";

const field = "w-full rounded-md border border-stoneWarm-200 bg-white px-3 py-2 text-sm";
function label(value: string) { return value.replaceAll("_", " "); }

export function OfflineMaintenance() {
  const [orders, setOrders] = useState<MaintenanceWorkOrder[]>([]);
  const [selected, setSelected] = useState<MaintenanceDetail | null>(null);
  const [rooms, setRooms] = useState<MaintenanceRoomOption[]>([]);
  const [staff, setStaff] = useState<MaintenanceStaffOption[]>([]);
  const [currentUser, setCurrentUser] = useState<{ id: string; email: string | null; role: "staff" | "admin" | "superadmin" } | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();

  async function reload(id?: string) {
    setOrders(await loadLocalWorkOrders());
    if (id) setSelected(await loadLocalMaintenanceDetail(id));
  }
  useEffect(() => { (async()=>{ try { const context=await loadMaintenanceOfflineContext(); setRooms(context.rooms); setStaff(context.staff); setCurrentUser(context.currentUser); await reload(); } catch { setMessage("No maintenance cache is available yet. Open Maintenance once while online."); } })(); }, []);
  function run(task:()=>Promise<void>, id?:string){setMessage(null);startTransition(async()=>{try{await task();await reload(id);setMessage(navigator.onLine?"Queued and syncing.":"Saved offline and queued for sync.");}catch(error){setMessage(error instanceof Error?error.message:"Maintenance action failed.");}})}
  const manager=currentUser?.role!=="staff";

  if(selected){const order=selected.workOrder;const canProgress=Boolean(currentUser&&(manager||order.assigned_to===currentUser.id));const transitionMap:Record<string,string[]>={open:["in_progress","cancelled"],assigned:["in_progress","on_hold","cancelled"],in_progress:["waiting_parts","on_hold","completed","cancelled"],waiting_parts:["in_progress","on_hold","cancelled"],on_hold:["in_progress","cancelled"],completed:[],cancelled:[]};const availableTransitions=transitionMap[order.status].filter(status=>manager||!(["completed","cancelled"].includes(status)));return <section className="grid gap-4"><button onClick={()=>setSelected(null)} className="w-fit text-sm font-semibold text-oliveMuted-700">Back to work orders</button><div className="border-b border-stoneWarm-200 pb-4"><p className="font-mono text-xs text-bronze-600">{order.work_order_number}</p><h2 className="mt-1 text-2xl font-semibold">{order.title}</h2><p className="mt-2 text-sm text-oliveMuted-600">{order.description}</p><p className="mt-2 text-xs capitalize text-oliveMuted-500">{label(order.status)} - {label(order.priority)} - {order.room_unit_name??"General property"}</p></div>
    {currentUser&&<><form onSubmit={event=>{event.preventDefault();const fd=new FormData(event.currentTarget);const description=String(fd.get("description")??"").trim();const priority=String(fd.get("priority"));run(()=>queueMaintenanceMutation("maintenance.edit",{workOrderId:order.id,title:order.title,description,category:order.category,priority,externalVendorName:order.external_vendor_name,scheduledFor:order.scheduled_for,expectedReturnAt:order.expected_return_at,estimatedCostUgx:order.estimated_cost_ugx},async()=>{const db=getLocalDb();await db.exec("UPDATE maintenance_work_orders SET description=?, priority=?, updated_at=? WHERE id=?",[description,priority,new Date().toISOString(),order.id]);await addLocalActivity({workOrderId:order.id,actorId:currentUser.id,action:"edited",previousStatus:order.status,newStatus:order.status,notes:"Description or priority updated offline."});}),order.id)}} className="grid gap-2 sm:grid-cols-[1fr_180px_auto]"><input name="description" defaultValue={order.description} required className={field}/><select name="priority" defaultValue={order.priority} className={field}>{MAINTENANCE_PRIORITIES.map(item=><option key={item}>{item}</option>)}</select><button className="rounded-md border border-stoneWarm-200 px-3 py-2 text-sm font-semibold">Save</button></form>
    {manager&&<form onSubmit={event=>{event.preventDefault();const assignedTo=String(new FormData(event.currentTarget).get("assignedTo")??"")||null;const next=assignedTo&&order.status==="open"?"assigned":!assignedTo?"open":order.status;run(()=>queueMaintenanceMutation("maintenance.assign",{workOrderId:order.id,assignedTo,note:"Assignment updated offline."},async()=>{const db=getLocalDb();await db.exec("UPDATE maintenance_work_orders SET assigned_to=?, status=?, updated_at=? WHERE id=?",[assignedTo,next,new Date().toISOString(),order.id]);await addLocalActivity({workOrderId:order.id,actorId:currentUser.id,action:"assigned",previousStatus:order.status,newStatus:next,notes:"Assignment updated offline."});}),order.id)}} className="flex gap-2"><select name="assignedTo" defaultValue={order.assigned_to??""} className={field}><option value="">Unassigned</option>{staff.map(person=><option key={person.id} value={person.id}>{person.name}</option>)}</select><button className="rounded-md border border-stoneWarm-200 px-3 py-2 text-sm font-semibold">Assign</button></form>}
    {canProgress&&<div className="flex flex-wrap gap-2">{availableTransitions.map(status=><button key={status} disabled={isPending||status===order.status} onClick={()=>{const resolution=status==="completed"?prompt("Resolution notes")?.trim()||null:null;const note=status==="cancelled"?prompt("Cancellation reason")?.trim()||null:`Status changed to ${label(status)} offline.`;if(status==="completed"&&!resolution)return;if(status==="cancelled"&&!note)return;run(()=>queueMaintenanceMutation("maintenance.status",{workOrderId:order.id,status,note,resolutionNotes:resolution,actualCostUgx:null},async(activityId)=>{const db=getLocalDb();const now=new Date().toISOString();await db.exec("UPDATE maintenance_work_orders SET status=?, completed_at=CASE WHEN ?='completed' THEN ? ELSE completed_at END, resolution_notes=CASE WHEN ?='completed' THEN ? ELSE resolution_notes END, updated_at=? WHERE id=?",[status,status,now,status,resolution,now,order.id]);await addLocalActivity({id:activityId,workOrderId:order.id,actorId:currentUser.id,action:`status_${status}`,previousStatus:order.status,newStatus:status,notes:note??resolution});}),order.id)}} className="rounded-md border border-stoneWarm-200 bg-white px-3 py-2 text-xs font-semibold capitalize">{label(status)}</button>)}</div>}
    <form onSubmit={event=>{event.preventDefault();const form=event.currentTarget;const note=String(new FormData(form).get("note")??"").trim();run(async()=>{await queueMaintenanceMutation("maintenance.note",{workOrderId:order.id,note},()=>addLocalActivity({workOrderId:order.id,actorId:currentUser.id,action:"note_added",previousStatus:order.status,newStatus:order.status,notes:note}));form.reset();},order.id)}} className="flex gap-2"><input name="note" required placeholder="Add note" className={field}/><button className="rounded-md border border-stoneWarm-200 px-3 py-2 text-sm font-semibold">Add</button></form>
    <form onSubmit={event=>{event.preventDefault();const input=event.currentTarget.elements.namedItem("image") as HTMLInputElement;const file=input.files?.[0];if(!file)return;run(async()=>{const processed=await shrinkImage(file);const dataUrl=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(processed)});await queueMaintenancePhoto({photoId:crypto.randomUUID(),workOrderId:order.id,actorId:currentUser.id,filename:processed.name,mimeType:processed.type,dataUrl,base64:dataUrl.split(",")[1]??""});input.value="";},order.id)}} className="grid gap-2 sm:grid-cols-[1fr_auto]"><input name="image" type="file" accept="image/*" className={field}/><button className="rounded-md border border-stoneWarm-200 px-3 py-2 text-sm font-semibold">Queue photo</button></form></>}
    <div className="grid gap-2 sm:grid-cols-3">{selected.photos.map(photo=><img key={photo.id} src={photo.storage_path} alt={photo.filename} className="aspect-video w-full border border-stoneWarm-200 object-cover"/>)}</div><ol className="grid gap-2 border-l border-stoneWarm-300 pl-4">{[...selected.activity].reverse().map(item=><li key={item.id}><p className="text-sm font-semibold capitalize">{label(item.action)}</p><p className="text-xs text-oliveMuted-600">{item.notes}</p></li>)}</ol>{message&&<p className="text-sm text-oliveMuted-700">{message}</p>}</section>}

  return <section className="grid gap-4"><div><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-bronze-500">Offline Maintenance</p><h2 className="mt-1 text-2xl font-semibold">Work Orders</h2><p className="mt-1 text-sm text-oliveMuted-600">Reads and writes use this device cache. Inventory changes remain unavailable offline.</p></div>{currentUser&&<details className="border border-stoneWarm-200 bg-white p-4"><summary className="cursor-pointer font-semibold">Create work order</summary><form onSubmit={event=>{event.preventDefault();const form=event.currentTarget;const fd=new FormData(form);const room=rooms.find(item=>item.id===String(fd.get("roomUnitId")))??null;const id=crypto.randomUUID();run(async()=>{await createLocalMaintenance({id,actorId:currentUser.id,roomUnitId:room?.id??null,roomTypeId:room?.room_type_id??null,assignedTo:null,externalVendorName:null,category:String(fd.get("category")),priority:String(fd.get("priority")),title:String(fd.get("title")??"").trim(),description:String(fd.get("description")??"").trim(),scheduledFor:null,expectedReturnAt:null,estimatedCostUgx:null});form.reset();});}} className="mt-3 grid gap-2 sm:grid-cols-2"><input name="title" required minLength={3} placeholder="Title" className={field}/><select name="roomUnitId" className={field}><option value="">General property</option>{rooms.map(room=><option key={room.id} value={room.id}>{room.room_type_title} - {room.unit_name}</option>)}</select><select name="category" defaultValue="other" className={field}>{MAINTENANCE_CATEGORIES.map(item=><option key={item}>{label(item)}</option>)}</select><select name="priority" defaultValue="normal" className={field}>{MAINTENANCE_PRIORITIES.map(item=><option key={item}>{item}</option>)}</select><textarea name="description" required minLength={5} placeholder="Description" className={`${field} sm:col-span-2`}/><button className="w-fit rounded-md bg-oliveMuted-600 px-4 py-2 text-sm font-semibold text-white">Queue work order</button></form></details>}
    <div className="grid gap-2">{orders.map(order=><button key={order.id} onClick={()=>void loadLocalMaintenanceDetail(order.id).then(setSelected)} className="grid gap-1 border border-stoneWarm-200 bg-white p-4 text-left"><span className="font-mono text-xs text-oliveMuted-500">{order.work_order_number}</span><span className="font-semibold">{order.title}</span><span className="text-xs capitalize text-oliveMuted-600">{label(order.status)} - {order.room_unit_name??"General property"}</span></button>)}{orders.length===0&&<p className="border border-dashed border-stoneWarm-300 p-4 text-sm text-oliveMuted-600">No cached maintenance work orders.</p>}</div>{message&&<p className="text-sm text-oliveMuted-700">{message}</p>}</section>;
}
